plugins {
    id "fabric-loom" version "${loom_version}"
    id "legacy-looming" version "${loom_version}"
    id 'java'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

loom {
    runs {
        client {
            programArgs("--accessToken", "0", "--version", "1.8.9", "--userProperties", "{}", "--tweakClass", "me.eldodebug.soar.injection.mixin.GlideTweaker")
            setMainClass("net.minecraft.launchwrapper.Launch")
        }
    }
}

legacyLooming {}

repositories {
    mavenCentral()
    maven { url 'https://raw.githubusercontent.com/BleachDev/cursed-mappings/main/' }
    maven { url 'https://repo.spongepowered.org/maven/' }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings(legacy.yarn(project.minecraft_version, project.yarn_build))

    implementation "net.minecraft:launchwrapper:1.12"
    implementation 'org.ow2.asm:asm-all:5.0.3'
    implementation 'org.json:json:20251224'
    implementation 'org.spongepowered:mixin:0.7.11-SNAPSHOT'
    implementation 'javax.annotation:javax.annotation-api:1.3.2'

    implementation(files('libs/lwjgl-soar.jar'))
    implementation(files('libs/lwjgl-soar-natives.jar'))
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"

    if (JavaVersion.current().isJava9Compatible()) {
        it.options.release = 8
    }
}

tasks.named("runClient") {
    javaLauncher = javaToolchains.launcherFor {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

jar {
    manifest.attributes(
            "MixinConfigs": 'mixins.soar.json',
            "TweakClass": 'me.eldodebug.soar.injection.mixin.GlideTweaker',
            "TweakOrder": 0,
            "Manifest-Version": 1.0,
            'FMLAT': 'soar_at.cfg'
    )
}

processResources {
    inputs.files "src/main/resources"
    outputs.dir "build/classes/main"
    copy {
        from("src/main/resources")
        into("build/classes/main")
    }
}